#!/bin/bash
xrdb $HOME/.Xresources
export DISPLAY=":1"
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace0/last-image -s /opt/stardust/wallpaper.png
startxfce4 &
sleep 1
sudo service dbus start
echo "while :
do
/home/stardust/.local/share/vscode/bin/code --no-sandbox --verbose --wait
sleep 2
done
" | bash
