#!/bin/bash
xrdb $HOME/.Xresources
export DISPLAY=":1"
startxfce4 &
sleep 1
echo "while :
do
chromium --no-sandbox --disable-dev-shm-usage --start-maximized --test-type --restore-last-session
window_ids=$(wmctrl -l | cut -f1 -d " ")
wmctrl -i -r $window_id -b add,fullscreen
sleep 2
done
" | bash
